name: flutter-create-aab-release

on:
  workflow_dispatch:
    inputs:
      aab-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      flutter-debug-symbols-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      merged-native-debug-symbols-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
  workflow_call:
    inputs:
      aab-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      flutter-debug-symbols-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      merged-native-libs-symbols-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: Slack Webhook URL
        required: true
      GITHUB_ENV_TOKEN:
        description: GITHUB_TOKEN
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ENV_TOKEN }}
        with:
          tag_name: v${{ inputs.version-code }}
          release_name: 'Release v${{ inputs.version-code }}'
          draft: false
          prerelease: false

      - name: Upload Release Asset - AAB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.aab-artifact-name }}.aab
          asset_name: ${{ inputs.aab-artifact-name }}${{ format('-{0}{1}', inputs.flavor, inputs.flavor != '' && '-' || '' ) }}v${{ inputs.version-code }}.aab
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset - Merged Native Debug Symbols
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.merged-native-debug-symbols-artifact-name }}.zip
          asset_name: ${{ inputs.merged-native-debug-symbols-artifact-name }}
          asset_content_type: application/zip

      - name: Upload Release Asset - Flutter Debug Symbols
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.flutter-debug-symbols-artifact-name }}.zip
          asset_name: ${{ inputs.flutter-debug-symbols-artifact-name }}
          asset_content_type: application/zip

      - name: Upload Release Asset - BOM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pubspec.lock
          asset_name: pubspec.lock
          asset_content_type: text/plain
