name: flutter-create-ipa-release

on:
  workflow_dispatch:
    inputs:
      ipa-artifact-name:
        description: IPA Artifact Name.
        required: true
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
      environment:
        description: Environment. e.g. staging, production
        required: false
        type: environment
      release-tag-suffix:
        description: Release tag prefix. e.g. -beta.1, -rc.1, ios, android
        required: false
        type: string
      runner-archive-artifact-name:
        description: Runner archive artifact name
        type: string
      runs-on:
        description: Runs on. e.g. ubuntu-latest, macos-latest
        required: false
        default: ubuntu-latest
        type: string
  workflow_call:
    inputs:
      ipa-artifact-name:
        description: IPA Artifact Name.
        required: true
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: true
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
      environment:
        description: Environment. e.g. staging, production
        required: false
        type: string
      release-tag-suffix:
        description: Release tag prefix. e.g. -beta.1, -rc.1, ios, android
        required: false
        type: string
      runner-archive-artifact-name:
        description: Runner archive artifact name
        type: string
      runs-on:
        description: Runs on. e.g. ubuntu-latest, macos-latest
        default: ubuntu-latest
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: Slack Webhook URL
        required: true
      GITHUB_ENV_TOKEN:
        description: GITHUB_TOKEN
        required: true

jobs:
  create-release:
    runs-on: ${{ inputs.runs-on}}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ENV_TOKEN }}
        with:
          tag_name: v${{ inputs.version-code }}${{ format('{0}{1}', inputs.release-tag-suffix != '' && '-' || '', inputs.release-tag-suffix ) }}
          release_name: 'Release v${{ inputs.version-code }}'
          draft: false
          prerelease: false

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Upload Release Asset - IPA
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ENV_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.ipa-artifact-name }}-${{ inputs.flavor }}/${{ inputs.ipa-artifact-name }}-${{ inputs.flavor }}.ipa
          asset_name: ${{ inputs.ipa-artifact-name }}${{ format('-{0}{1}', inputs.flavor, inputs.flavor != '' && '-' || '' ) }}v${{ inputs.version-code }}.ipa
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - Runner Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ENV_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ inputs.runner-archive-artifact-name}}/Runner.xcarchive
          asset_name: Runner.xcarchive
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - BOM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ENV_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bom/pubspec.lock
          asset_name: pubspec.lock
          asset_content_type: text/plain

      - name: The job has failed
        if: ${{ failure() && inputs.flavor == '' }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_MESSAGE: 'Unable to complete IPA `release-create` workflow for `${{ github.event.repository.name }}` :ios: :x:.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
