name: push-ipa-to-test-flight

on:
  workflow_dispatch:
    inputs:
      runner:
        description: Runner. e.g. self-hosted
        required: false
        default: macos-latest
        type: string
      environment:
        description: Environment. e.g. stage
        required: false
        type: environment
      ipa-artifact-name:
        description: IPA artifact name. e.g. ios.ipa
        required: false
        default: ios.ipa
        type: string
      ipa-file-name:
        description: IPA file name. e.g. ios.ipa
        required: false
        type: string
      fastlane-lane:
        description: Fastlane lane
        type: string
      fastlane-args:
        description: Fastlane args. e.g. flavor:stage
        type: string
      app-name:
        description: App Name
        type: string
        default: App Name
        required: true
      final-ipa-file-name:
        description: Final IPA file name.
        type: string
        required: true
  workflow_call:
    inputs:
      runner:
        description: Runner. e.g. self-hosted
        default: macos-latest
        required: false
        type: string
      environment:
        description: Environment. e.g. stage
        required: false
        type: string
      ipa-artifact-name:
        description: IPA artifact name. e.g. ios.ipa
        required: false
        default: ios.ipa
        type: string
      ipa-file-name:
        description: IPA file name. e.g. ios.ipa
        required: false
        type: string
      app-name:
        description: App Name
        type: string
        default: App Name
        required: true
      fastlane-lane:
        description: Fastlane lane
        type: string
      fastlane-args:
        description: Fastlane args. e.g. flavor:stage
        type: string
        required: false
      final-ipa-file-name:
        description: Final IPA file name.
        type: string
        required: true
    secrets:
      APPSTORE_CONNECT_JSON_BASE64:
        description: Fastlane app store connect credential json
        required: true
      GITHUB_ENV_TOKEN:
        description: Github token to download release
        required: true

jobs:
  push-ipa-to-test-flight:
    name: Push IPA to TestFlight
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Validate AAB Inputs
        run: |
          if [ -z "${{ inputs.ipa-file-name }}" ] && [ -z "${{ inputs.ipa-artifact-name }}" ]; then
            echo "Either ipa-file-name or ipa-artifact-name is required"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - if: ${{ inputs.ipa-artifact-name != '' && inputs.ipa-file-name == '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.ipa-artifact-name }}

      - if: ${{ inputs.ipa-artifact-name != '' && inputs.ipa-file-name == '' }}
        name: Move IPA Artifact
        run: |
          mv ${{ inputs.app-name }}.ipa ${{ inputs.final-ipa-file-name }}.ipa

      - if: ${{ inputs.ipa-file-name != '' && inputs.ipa-artifact-name == '' }}
        name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: get-latest-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_ENV_TOKEN }}

      - if: ${{ inputs.ipa-file-name != '' && inputs.ipa-artifact-name == '' }}
        name: Download IPA File from Latest Release
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ steps.get-latest-release.outputs.release }}
          fileName: '${{ inputs.ipa-file-name }}-${{ steps.get-latest-release.outputs.release }}.ipa'
          out-file-path: release

      - if: ${{ inputs.ipa-file-name != '' && inputs.ipa-artifact-name == '' }}
        name: Move IPA Release
        run: mv ./release/${{ inputs.ipa-file-name }}.ipa ${{ inputs.final-ipa-file-name }}.ipa

      - name: Prepare App Store Connect Credential
        run: |
          echo "${{ secrets.APPSTORE_CONNECT_JSON_BASE64 }}" | base64 --decode > ios/fastlane/api.json

      - name: Upload IPA to TestFlight
        run: |
          cd ios && fastlane ${{ inputs.fastlane-lane }} ${{ inputs.fastlane-args }}

      - name: Clean Up App Store Connect Credentials
        if: ${{ always() }}
        run: rm -f ios/fastlane/api.json

      - if: ${{ failure() }}
        name: The job has failed
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_MESSAGE: 'Push IPA :ios: to Test Flight for `${{ github.event.repository.name }}` failed :x:.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
