name: push-aab-to-google-play-store

on:
  workflow_dispatch:
    inputs:
      aab-file-name:
        description: AAB File Name.
        required: false
        type: string
      aab-artifact-name:
        description: AAB Artifact Name.
        required: false
        type: string
  workflow_call:
    inputs:
      aab-file-name:
        description: AAB File Name.
        required: false
        type: string
      aab-artifact-name:
        description: AAB Artifact Name.
        required: false
        type: string
    secrets:
      GITHUB_ENV_TOKEN:
        description: GITHUB_ENV_TOKEN
        required: true

jobs:
  download-latest-release-and-push-to-google-play:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.aab-artifact-name == '' && inputs.aab-file-name != '' }}
        name: Get latest release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: get-latest-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_ENV_TOKEN }}

      - if: ${{ inputs.aab-artifact-name == '' && inputs.aab-file-name != '' }}
        name: release-downloader
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ steps.get-latest-release.outputs.release }}
          fileName: '${{ inputs.aab-file-name }}-${{ steps.get-latest-release.outputs.release }}.aab'
          out-file-path: release

      - name: LS
        run: ls -R
